-- MySQL Script generated by MySQL Workbench
-- Fri Aug 25 13:21:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema family_tree
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `family_tree` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `family_tree` ;

-- -----------------------------------------------------
-- Table `family_tree`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_tree`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_tree`.`family_trees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_tree`.`family_trees` (
  `tree_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `tree_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tree_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `family_tree`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_tree`.`family_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_tree`.`family_members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `tree_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `tree_id_idx` (`tree_id` ASC) VISIBLE,
  CONSTRAINT `member_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `family_tree`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `tree_id`
    FOREIGN KEY (`tree_id`)
    REFERENCES `family_tree`.`family_trees` (`tree_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `family_tree`.`family_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `family_tree`.`family_relationship` (
  `relationship_id` INT NOT NULL AUTO_INCREMENT,
  `child_id` INT NOT NULL,
  `mother_id` INT NULL DEFAULT NULL,
  `father_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`relationship_id`),
  UNIQUE INDEX `child_id_UNIQUE` (`child_id` ASC) VISIBLE,
  INDEX `mother_id_idx` (`mother_id` ASC) VISIBLE,
  INDEX `father_id_idx` (`father_id` ASC) VISIBLE,
  CONSTRAINT `child_id`
    FOREIGN KEY (`child_id`)
    REFERENCES `family_tree`.`family_members` (`member_id`)
    ON DELETE CASCADE,
  CONSTRAINT `father_id`
    FOREIGN KEY (`father_id`)
    REFERENCES `family_tree`.`family_members` (`member_id`)
    ON DELETE SET NULL,
  CONSTRAINT `mother_id`
    FOREIGN KEY (`mother_id`)
    REFERENCES `family_tree`.`family_members` (`member_id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
